version: '3'
services:
  web:
    container_name: nginx
    image: nginx:latest
    restart: always
    ports:
      - "8084:80"
    volumes:
      - ./www:/www
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    container_name: php
    build: 
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
    - ./www:/www
    links:
      - db
  db:
    container_name: mysql
    image: mysql:5.7
    ports:
    - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teste